### ISSUE TITLE
Incorrect padding

### ISSUE THREAD

**Issue by vicmol53** [Chavithra/degiro-connector#106]
...\envs\degiro\lib\base64.py", line 205, in b32decode
    raise binascii.Error('Incorrect padding')
binascii.Error: Incorrect padding

Hello community, 
Trying to connect with script  'connection_2fa.py'  then this error occurs. ?

btw: Have a nice Christmas and  happy new year
Victor

**Comment by Nico-lezicos** [comment]
I have the same trouble here, thank you

**Comment by paulomiguelfferreira** [comment]
I also have this same problem, help please. Thank-you.

**Comment by romanpeters** [comment]
You need to use the TOTP seed key instead of a generated TOTP code.

**Comment by Chavithra** [comment]
Hello there,

@romanpeters mentioned I think you are using the `one_time_password` number instead of the `totp_secret_key`.

There is a good example on how to do it here:
https://github.com/Chavithra/degiro-connector/issues/87#issuecomment-1216386035

Closing this issue.

Feel free to create another issue if you still can't use 2FA.
