### ISSUE TITLE
Impossible to check a STOP_LOSS order

### ISSUE THREAD

**Issue by b-aeby** [Chavithra/degiro-connector#11]
Hello,

I can't check a stoploss order, an internal server error is returned:

```
order = Order(
    action=Order.Action.SELL,
    order_type=Order.OrderType.STOP_LOSS,
    stop_price=110.0,
    product_id=4457,
    size=1,
    time_type=Order.TimeType.GOOD_TILL_CANCELED,
)
```

```
CRITICAL:trading.basic:500
CRITICAL:trading.basic:{"errors":[{"text":"Internal server error"}]}
```

The same datas as a json send to the check order url yields no error and allows to confirm the order.
```
sellOrder = {
            'buySell': 1,               # buy = 0, sell = 1
            'orderType': 3,             # stoploss order
            'productId': 4457,     # SAP id
            'size': 1,                # number of shares to buy/sell
            'timeType': 1,              # day = 1, permanent = 3
            'stopPrice': 110.0,     # stop loss
            }
```

I have a custody account... BUY orders are OK

Could you please provide a working example for each order type ?

Congratulations for the awesome job you've done so far. 
Regards
Benjamin

**Comment by Chavithra** [comment]
Hello there,

**Issue**
I was able to reproduce this issue.

The library sends the price for all `OrderType` inside the field : `price`.

But for a `STOP_LOSS`, the API expects the price to be inside the field : `stopPrice`.

**State**
This issue was fixed and a new release was published.

**Feedback**
Can you tell me if that works on your side ?

Thanks for reporting this bug.

**Comment by b-aeby** [comment]
Hi,

Great and fast response!
I just checked and everything works fine now including confirmation of the order.

Thanks
