### ISSUE TITLE
`get_account_overview` doesn't return the proper information.

### ISSUE THREAD

**Issue by ctasada** [Chavithra/degiro-connector#135]
I was trying to get the AccountOverview info and the returned info didn't match with my expectations. After looking into the code I found the issue

https://github.com/Chavithra/degiro-connector/blob/94d1b6fa463f27d7c5c9e9cde11b94493ae2d2a1/degiro_connector/trading/actions/action_get_account_overview.py#L75

which should be `url = urls.ACCOUNT_OVERVIEW`

I was trying to provide a PR, but I also found that running

`poetry run pytest -m core` is failing on multiple tests, so I don't feel confident providing a PR at the current time.

Thanks for the great work you're doing and I wish I can be more helpful in future contributions.

**Comment by Chavithra** [comment]
Hello @ctasada,

**ACCOUNT OVERVIEW**
Thank you for reporting this issue.

I have fixed it and released a new version.

**ABOUT TESTS**
Due to a recent and major refactoring of the models: `pytest` tests are obsolete.

Although it is not as convenient than `pytest`, for now we can test a feature by running the matching example module.

Thanks

**Comment by ctasada** [comment]
Hey @Chavithra thank you for the quick fix.

I can confirm that the new release is working fine.
