### ISSUE TITLE
various requests return http 403/404

### ISSUE THREAD

**Issue by paveldomsa** [Chavithra/degiro-connector#3]
Hi,
I can successfully log in and get config table via trading_api.get_config(). Returned data seems to be ok.
Since that nothing works as expected. For example:
favourites_list = trading_api.get_favourites_list()
 results in:
DEBUG:urllib3.connectionpool:https://trader.degiro.nl:443 "GET /pa/secure/favourites/lists?intAccount=1536831&sessionId=384815D9922F04E8EB92614449202A7B.prod_b_113_2 HTTP/1.1" 404 None
CRITICAL:trading.basic:404
CRITICAL:trading.basic:{"errors":[{"text":"No corresponding resource found"}]}
CRITICAL:trading.basic:'data'
False

next:
request_list = Update.RequestList()
request_list.values.extend(
    [
        Update.Request(
            option=Update.Option.TOTALPORTFOLIO,
            last_updated=0,
        ),
    ]
)
print (request_list)

update = trading_api.get_update(request_list=request_list, raw=False)
update_dict = pb_handler.message_to_dict(message=update)

results in:
DEBUG:urllib3.connectionpool:https://trader.degiro.nl:443 "GET /trading/secure/v5/update/1535031;jsessionid=AEE095C89F409EE4569DCA2829EF16B1.prod_b_113_2?totalPortfolio=0&intAccount=1535031&sessionId=AEE095C89F409EE4569DCA2829EF16B1.prod_b_113_2 HTTP/1.1" 403 None
{'response_datetime': '2021-01-25T13:41:56.123899Z'}

Any ideas, thanks?

**Comment by Chavithra** [comment]
Hello there,

I have split my answer into five parts :
1. Credentials in your message
2. Good news
3. Bad news
4. One way I have reproduced this issue
5. Question

**1. Credentials in your message.**

There is a "intAccount" in your message.

If this is your personal "intAccount", it would be better to remove it from the message and then remove the history of modification.

**2. Good news**
The method "get_favourites_list" works on my side.

I have run the example from the library and I have the right result.

**3. Bad news**
This probably means the issue is on the test you made.

**4. One way I have reproduced this issue**
I might have spotted the issue : when I use the wrong "intAccount" I have the same error.

**5. Question**
Can you tell me how you get your "intAccount" ?

Thanks

**Comment by paveldomsa** [comment]
Thanks for quick response. 
Here is how i get it: 
config_table = trading_api.get_config()
user_token = config_table['clientId']

**Comment by Chavithra** [comment]
Ok, I understand now.

**Issue**
The "user_token" was used instead of the "int_account".

These two identifiers are not the same thing :
- user_token
- int_account

**Solution**
One way to get the "int_account" is to use the method : "get_client_details".

More information about how to get the "int_account" is available in the documentation of this library.

Hope that helps

**Comment by SomethingWithComputers** [comment]
Hey there, I might be having a similar issue. I am using the int_account (intAccount from get_client_details) as a user_token in this example: (https://github.com/dasbrod/degiro-connector/blob/master/examples/quotecast/realtime_data.py) and I'm getting a 502. Is there a different user_token I can find somewhere? It said the user_token is inside the config, but I couldn't really find anything similar..

By the way, there seems to be an error on the `from quotecast.pb.quotecast_pb2 import Request` line.

I changed it to `from quotecast.pb.quotecast_pb2 import Quotecast` and the `request = Request()` into `request = Quotecast.Request()` which seems to silence that warning, though I'm not super sure if this is the correct way..

Thanks in advance :)!

**Comment by paveldomsa** [comment]
it helped. thanks.
