### ISSUE TITLE
get stocks details

### ISSUE THREAD

**Issue by paveldomsa** [Chavithra/degiro-connector#4]
Hi,
is there a way how to get stock details (same as i could get via RequestLookup or RequestStocks) when i have just stocks id (for example (AMD id is 5462588).

Basically i have portfolio, i get it via
request_list = Update.RequestList()
request_list.values.extend(
    [
        Update.Request(
            option=Update.Option.PORTFOLIO,
            last_updated=0,
        ),
    ]
)
print (request_list)

update = trading_api.get_update(request_list=request_list, raw=False)

and i need to get vwid and other stock details to pass to quotecast.
documentation says 
3. How to get a "vwd_id" ?

One way to get the "vwd_id" of a product : fetch details about that product using the "lookup" (search by name) feature of this library.

are there any other ways (i can't search by names since portfolio request doesn't provide any names).

Thanks

**Comment by Chavithra** [comment]
Hi,

1. Use case
2. Does the website do it ?
3. Reverse engineering
4. New method
5. Feedback

**1. Use case**
That's an interesting use case.

I too need to link these two elements :
* vwd_id
* product_id

I am using matching tables to do so.

**2. Does the website do it ?**

I took a look at the website it seems to manage to link these elements :
* product_id
* product name

**3. Reverse engineering**
I have checked the communication between my browser and Degiro's API.

Turns out there is an endpoint to get products details from their ids.

**4. New method**
I have added a new method called :
* get_products_info

I have also updated the documentation.

This method seems to do the job.

**5. Feedback**
I am interested in having feedback : does it work on your side too ?

See ya

**Comment by paveldomsa** [comment]
it does work for me too. 
nice and quick job. 
thanks
