### ISSUE TITLE
Realtime poller detection?

### ISSUE THREAD

**Issue by fbondeaux** [Chavithra/degiro-connector#7]
Hey guys, I am wondering what the probability of detection is when you use realtime_poller in a loop? There are cases that DG detects certain automatic operations and gives warnings. Does anyone know if there is protection in the code of the package; random seconds api calls or something like that? Furthermore, love this package guys!

**Comment by Chavithra** [comment]
Hi,

**Polling**
I don't know about detection.

But polling `Quotecast` in loop seems to be how this endpoint is meant to be used.

Since this is exactly how Degiro's website is doing it : it polls `Quotecast` in loop.

What I wouldn't recommend doing : 
- Reopening a session a each call.
- Subscribing to too much data in the same session.

I have seen that some library like @pladaria's one reopening a session at each call.

That can make sense if you want an update every minute or so.

But if you need real time data it doesn't make sense to reopen the connection every second.

**Trading**
I think Degiro cares more about the automatic trading operations (transactions) than the `Quotecast`.

But I might be wrong : it would be interesting to check in the  `Terms of Agreement `.

**Random seconds**
There is no random wait in this library features.

**Library**
It's cool that you like this library.

Maybe you can like the repository to show your appreciation.

Hope that answers to some of your questions

**Comment by fbondeaux** [comment]
Can you have a look at the routine of options data stream in real time? It seems that or the dataprovider blocks data or that it only returns value if something changes in the bid ask

**Comment by fbondeaux** [comment]
Another thing as well: it seems that option prices are being rounded to two decimals. Can this be changed to 3 or 4?

**Comment by Chavithra** [comment]
These seem to be questions for another issue.

I am closing this issue.

Feel free to open another issue if you want to discuss about these points.
